Reuse docker client
arnef/monitgo pull request #7
Opened 2021-10-06 20:07 UTC by jasperem

2021-10-11 15:40 UTC, arnef commented on interal/watcher/node/container_snapshot.go
> +const MAX_ROUTINES = 10
do you still need them? and if so it would be nice to be able to set them via config

2021-10-11 15:41 UTC, arnef requested changes

2021-10-11 15:41 UTC, arnef commented on interal/node-exporter/api/handleDocker.go
> +		log.Error(err, ", ", a.host)
use `fmt.Errorf` to format the message

2021-10-11 17:14 UTC, jasperem commented on interal/watcher/node/container_snapshot.go
> +const MAX_ROUTINES = 10
In my opinion it is nicer to set a maximum value for parallel routines, but doing that via configuration is a good point.

2021-10-11 19:55 UTC, jasperem commented on interal/watcher/node/container_snapshot.go
> +const MAX_ROUTINES = 10
go says no https://golang.org/doc/faq#number_cpus

2021-10-13 19:10 UTC, arnef approved these changes

2021-10-13 19:11 UTC, merged